jobs:
  build:
    name: Dependencies
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repository
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Run snapshot action
      uses: mikepenz/gradle-dependency-submission@v0.9.1
name: build
on:
  repository_dispatch:
    types: trigger-ga___dependencies.yml
