jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.NIGHTLY_BUILD_GH_TOKEN }}
      id: set-vars
      name: Set Vars
      run: 'echo "LATEST_STABLE_TAG=$(gh release list -R ${{ github.repository}} |
        grep -v nightly | awk ''{ print $1}'' | head -1)"  >> $GITHUB_ENV

        echo "Latest Stable Tag: $LATEST_STABLE_TAG"

        echo "NIGHTLY_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV

        echo "Creating for Nightly: $NIGHTLY_DATE"

        '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.NIGHTLY_BUILD_GH_TOKEN }}
      id: create-release
      name: Create Release
      run: 'gh release create  nightly-${NIGHTLY_DATE} -R ${{github.repository}} --title
        "MapTool Nightly ${NIGHTLY_DATE}"  --notes "MapTool Nightly Build for ${NIGHTLY_DATE}"
        --generate-notes -p --target develop

        '
name: Nightly Release
on:
  repository_dispatch:
    types: trigger-ga___nightly-publish.yml
