jobs:
  build:
    name: ${{ matrix.os }} w/JDK ${{ matrix.java }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Git checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Cache Gradle
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        path: ~/.gradle/caches
        restore-keys: '${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      name: Build with Gradle
      uses: GabrielBB/xvfb-action@v1.0
      with:
        run: ./gradlew build --no-daemon
    strategy:
      fail-fast: false
      matrix:
        distribution:
        - temurin
        java:
        - '21'
        os:
        - windows-latest
        - ubuntu-latest
        - macOS-latest
  formatting:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Git checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '21'
    - continue-on-error: true
      name: spotlessCheck
      run: ./gradlew spotlessCheck
name: Build Verification
on:
  repository_dispatch:
    types: trigger-ga___verify-build.yml
